### ISSUE TITLE
mpv-install.bat breaks file saving in Microsoft Edge (Chromium)

### ISSUE THREAD

**Issue by paperclip-dayo** [shinchiro/mpv-winbuild-cmake#85]
Running mpv-install.bat will break "save" function in Edge (Chromium) when trying to save any file formats that get associated with mpv; Edge will offer to open the file instead of saving. Doesn't matter if you press Save, Save As/Page or use a Download function from the native browser player.
This only happens with this mpv build, not with any other player or mpvnet.

Repro:
Unpack mpv
Do not run mpv-install.bat
Open Edge, try saving random webm with Edge e.g. something from https://boards.4channel.org/wsg/, "save" window should pop up and file should be saved successfully
Close Edge
Run mpv-install.bat
Open Edge and try saving the same webm again, Edge will offer to open the file instead of saving
**---note:** _it may be necessary to select mpv as default player in Default apps but in my case Edge save breaks even when mpv isn't set as default (but mpv-install.bat is active). 

Windows 10 2004 but this also affected 1903/9 and possibly older builds.
Edge links (I tested Canary but this happens on all channels): https://www.microsoftedgeinsider.com/en-us/download/

**Comment by planetarian** [comment]
This is still busted. It's impossible to save any file which mpv is set to open by default. You're only given the option to 'open' the file, even when you use rightclick -> save ....

**Comment by hooke007** [comment]
It seems the latest edge has fixed?

**Comment by shinchiro** [comment]
I'm assuming it's fixed in edge then

**Comment by floppyD** [comment]
Still happening here

https://user-images.githubusercontent.com/29208110/121939296-42036400-cd23-11eb-8c47-11c1371dd71c.mp4

mpv-x86_64-20210613-git-03b9f8e
Edge 91.0.864.48
Windows 10 19043.1052

**Comment by hooke007** [comment]
> Still happening here

Try to uninstall and reinstall the latest build will fix.
